"""Deterministic demo ``factory.json`` generator.

This exists for one narrow case: the dashboard is pointed at a factory path that does
not exist yet, and a stakeholder still needs something to look at. It is **not** a
second factory-configuration system -- the generated file is an ordinary
``factory.json`` consumed by the existing simulator, and once written it is treated
like any other operator-supplied configuration.

Every rule enforced here comes from ``simulation/src/ConfigLoader.cpp`` (mirrored in
:mod:`dashboard.factory.validator`), plus two dashboard demo policies:

* DARK corridors are capped at :data:`~dashboard.factory.validator.MAX_DARK_CORRIDOR_POLICY`
  stations.
* The result is tagged with ``_demo`` metadata so it is never mistaken for a
  measured or engineered plant definition.

The output is a pure function of ``seed``.
"""

from __future__ import annotations

import random
from typing import Any

from dashboard.factory.validator import MAX_DARK_CORRIDOR_POLICY, validate_factory

#: Marker key written into every generated file.
DEMO_MARKER = "_demo"

#: Value of ``_generated_by`` in generated files.
GENERATOR_ID = "dashboard.factory.generator"

GENERATOR_VERSION = 1

DEMO_NOTE = (
    "Illustrative demo/default factory configuration generated by the DigitalTwin.ai "
    "dashboard because no factory.json existed at the configured path. Station "
    "parameters are prototype values, not measured plant data. Replace this file with "
    "the real plant configuration before drawing operational conclusions."
)

MIN_DEMO_STATIONS = 30
MAX_DEMO_STATIONS = 50

# Ordered line segments. Weights distribute the interior stations between the source
# and the sink; each segment optionally ends with an INSPECTION gate.
_SEGMENTS: tuple[tuple[str, str, float, bool], ...] = (
    ("Body Shop", "BODY", 0.30, True),
    ("Paint", "PAINT", 0.22, True),
    ("General Assembly", "GA", 0.32, False),
    ("Final Test", "TEST", 0.16, True),
)

_SEGMENT_STATION_NAMES: dict[str, tuple[str, ...]] = {
    "BODY": (
        "Underbody Weld", "Floor Pan Weld", "Side Frame Weld", "Roof Fit",
        "Weld Verification", "Door Aperture Weld", "Seam Dress", "Body Geometry Scan",
        "Panel Alignment", "Structural Adhesive", "Hem Flange Set", "Body Framing",
    ),
    "PAINT": (
        "Sealer Apply", "E-Coat Load", "E-Coat Bake", "Surface Check", "Primer Spray",
        "Primer Bake", "Topcoat Spray", "Clearcoat Spray", "Paint Cure", "Wax Injection",
    ),
    "GA": (
        "Glass Install", "Instrument Install", "Trim Fit", "Seat Install",
        "Wheel Install", "Fluid Fill", "Harness Route", "Door Reattach",
        "Bumper Fit", "Headliner Install", "Console Fit", "Battery Install",
        "Cooling Fill", "Steering Set",
    ),
    "TEST": (
        "Electrical Test", "Dynamic Test", "Brake Test", "Alignment Test",
        "Water Ingress Test", "Final Audit", "Road Simulation",
    ),
}


def _archetype_plan(
    interior_count: int, segment_slices: list[tuple[str, str, int, int, bool]], rng: random.Random
) -> dict[int, str]:
    """Assign an archetype to every interior station index (1-based line position)."""
    plan: dict[int, str] = {}
    for _label, _code, start, end, gated in segment_slices:
        for index in range(start, end + 1):
            plan[index] = "AUTOMATED"
        if gated and end >= start:
            plan[end] = "INSPECTION"

    # Manual rework/finishing stations: roughly one in eight interior stations, never
    # on an inspection gate, and never immediately adjacent to another manual station.
    manual_target = max(3, round(interior_count * 0.13))
    candidates = [index for index, archetype in sorted(plan.items()) if archetype == "AUTOMATED"]
    rng.shuffle(candidates)
    chosen: list[int] = []
    for index in candidates:
        if len(chosen) >= manual_target:
            break
        if any(abs(index - taken) < 2 for taken in chosen):
            continue
        chosen.append(index)
    for index in chosen:
        plan[index] = "MANUAL"
    return plan


def _coverage_for(archetype: str, rng: random.Random) -> str:
    """Uneven, archetype-aware sensor coverage."""
    if archetype == "MANUAL":
        # Manual cells are the classic blind spots on a real line.
        return "NONE"
    if archetype == "INSPECTION":
        return "PARTIAL" if rng.random() < 0.8 else "HIGH"
    draw = rng.random()
    if draw < 0.62:
        return "HIGH"
    if draw < 0.92:
        return "PARTIAL"
    return "NONE"


def _cycle_parameters(archetype: str, rng: random.Random) -> tuple[int, float, int]:
    """Return ``(meanCycleTimeMs, cycleTimeCV, bufferCapacity)`` for an archetype."""
    if archetype == "MANUAL":
        return rng.randrange(54_000, 66_000, 500), round(rng.uniform(0.16, 0.21), 3), rng.randint(1, 2)
    if archetype == "INSPECTION":
        return rng.randrange(48_000, 58_000, 500), round(rng.uniform(0.10, 0.14), 3), rng.randint(2, 3)
    return rng.randrange(36_000, 52_000, 500), round(rng.uniform(0.08, 0.13), 3), rng.randint(3, 5)


def _select_dark_corridors(
    stations: list[dict[str, Any]], rng: random.Random
) -> list[tuple[int, int]]:
    """Pick non-adjacent internal DARK corridors of 2-3 stations, avoiding INSPECTION.

    Mirrors ``ConfigLoader``: corridors live in ``[1, n-2]``, must be at least two
    stations long, must not contain an INSPECTION station, and consecutive corridors
    must be separated by at least one LIGHT station.
    """
    count = len(stations)
    last_allowed_end = count - 2
    eligible = [
        index
        for index in range(1, last_allowed_end + 1)
        if stations[index]["archetype"] != "INSPECTION"
    ]
    eligible_set = set(eligible)

    corridors: list[tuple[int, int]] = []
    target = rng.choice((2, 2, 3))
    # Spread the corridors across the line by giving each one its own band, instead of
    # letting a greedy sweep cluster them all upstream.
    band = max(3, (last_allowed_end - 1) // target)
    min_start = 2

    def place(low: int, high: int) -> bool:
        span = min(rng.choice((2, 2, 3)), MAX_DARK_CORRIDOR_POLICY)
        for start in range(max(low, min_start), high - span + 2):
            end = start + span - 1
            if end > last_allowed_end:
                break
            if all(index in eligible_set for index in range(start, end + 1)):
                corridors.append((start, end))
                return True
        return False

    for position in range(target):
        low = 1 + position * band + rng.randint(0, max(0, band // 3))
        high = min(last_allowed_end, 1 + (position + 1) * band)
        if high - low < 1:
            continue
        if place(low, high):
            # +2 keeps at least one LIGHT station between consecutive corridors.
            min_start = corridors[-1][1] + 2

    if len(corridors) < 2:
        # Fallback sweep, so a line with awkward inspection placement still gets the
        # LIGHT/DARK contrast the dashboard is meant to show.
        while len(corridors) < 2 and place(min_start, last_allowed_end):
            min_start = corridors[-1][1] + 2

    corridors.sort()
    return corridors


def _zone_label(stations: list[dict[str, Any]], start: int) -> str:
    return str(stations[start].get("_segment", "Line"))


def generate_demo_factory(seed: int = 42) -> dict[str, Any]:
    """Build a deterministic, simulator-valid demo factory definition.

    The same ``seed`` always produces byte-identical output. Raises ``RuntimeError``
    if the result would not satisfy the simulator contract, so a broken generator can
    never write an unusable ``factory.json``.
    """
    rng = random.Random(seed)
    count = rng.randint(MIN_DEMO_STATIONS + 2, MAX_DEMO_STATIONS - 4)
    interior_count = count - 2

    # Slice the interior into ordered line segments.
    segment_slices: list[tuple[str, str, int, int, bool]] = []
    cursor = 1
    remaining = interior_count
    for position, (label, code, weight, gated) in enumerate(_SEGMENTS):
        if position == len(_SEGMENTS) - 1:
            size = remaining
        else:
            size = max(3, round(interior_count * weight))
            size = min(size, remaining - 3 * (len(_SEGMENTS) - position - 1))
        segment_slices.append((label, code, cursor, cursor + size - 1, gated))
        cursor += size
        remaining -= size

    archetypes = _archetype_plan(interior_count, segment_slices, rng)

    segment_of: dict[int, tuple[str, str]] = {}
    name_of: dict[int, str] = {}
    for label, code, start, end, _gated in segment_slices:
        pool = _SEGMENT_STATION_NAMES[code]
        for offset, index in enumerate(range(start, end + 1)):
            segment_of[index] = (label, code)
            name_of[index] = pool[offset % len(pool)]

    stations: list[dict[str, Any]] = []
    for index in range(count):
        if index == 0:
            archetype = "AUTOMATED"
            name = "Body Infeed"
            label, code = "Body Shop", "BODY"
        elif index == count - 1:
            archetype = "AUTOMATED"
            name = "Vehicle Dispatch"
            label, code = "Final Test", "TEST"
        else:
            archetype = archetypes[index]
            label, code = segment_of[index]
            base = name_of[index]
            if archetype == "MANUAL":
                name = f"Manual {base}"
            elif archetype == "INSPECTION":
                name = f"{label} Inspection"
            else:
                name = base

        mean_cycle, cv, buffer_capacity = _cycle_parameters(archetype, rng)
        if index == 0:
            mean_cycle, cv, buffer_capacity = rng.randrange(34_000, 38_000, 500), 0.08, 0
        elif index == count - 1:
            mean_cycle, cv, buffer_capacity = rng.randrange(33_000, 37_000, 500), 0.08, 4

        station: dict[str, Any] = {
            "id": index,
            "name": f"{name} {index:02d}",
            "archetype": archetype,
            "meanCycleTimeMs": mean_cycle,
            "cycleTimeCV": cv,
            "bufferCapacity": buffer_capacity,
            "sensorCoverage": _coverage_for(archetype, rng),
        }
        if index == 0:
            station["source"] = True
            station["sensorCoverage"] = "HIGH"
        if index == count - 1:
            station["sink"] = True
        station["_segment"] = label
        stations.append(station)

    corridors = _select_dark_corridors(stations, rng)

    # A DARK corridor is only interesting when at least one cell inside it is
    # genuinely unobserved, so force one manual, sensorless station per corridor.
    for start, end in corridors:
        blind = rng.randint(start, end)
        stations[blind]["archetype"] = "MANUAL"
        stations[blind]["sensorCoverage"] = "NONE"
        mean_cycle, cv, buffer_capacity = _cycle_parameters("MANUAL", rng)
        stations[blind]["meanCycleTimeMs"] = mean_cycle
        stations[blind]["cycleTimeCV"] = cv
        stations[blind]["bufferCapacity"] = buffer_capacity
        if not stations[blind]["name"].startswith("Manual "):
            stations[blind]["name"] = f"Manual {stations[blind]['name']}"

    dark_zones: list[dict[str, Any]] = []
    checkpoints: list[dict[str, Any]] = []
    for position, (start, end) in enumerate(corridors, start=1):
        label = _zone_label(stations, start)
        dark_zones.append(
            {
                "id": f"DZ_DEMO_{position:02d}",
                "name": f"{label} Unobserved Corridor {position}",
                "startStationId": start,
                "endStationId": end,
                "observability": {
                    "sensorTelemetry": True,
                    "manualChecks": True,
                    "checkpoints": True,
                },
            }
        )
        # RFID identifies the unit; POWER_DRAW is station/population evidence only.
        checkpoints.append(
            {
                "id": f"CP_DZ{position:02d}_RFID",
                "stationId": start,
                "type": "RFID",
                "progress": round(rng.uniform(0.40, 0.55), 2),
                "reliability": round(rng.uniform(0.86, 0.94), 2),
                "falsePositiveRate": round(rng.uniform(0.0, 0.02), 3),
                "identifiesUnit": True,
            }
        )
        checkpoints.append(
            {
                "id": f"CP_DZ{position:02d}_POWER",
                "stationId": end,
                "type": "POWER_DRAW",
                "progress": round(rng.uniform(0.50, 0.65), 2),
                "reliability": round(rng.uniform(0.80, 0.90), 2),
                "falsePositiveRate": 0.0,
                "identifiesUnit": False,
            }
        )

    # One LIGHT-zone checkpoint downstream of every corridor, for contrast.
    dark_members = {index for start, end in corridors for index in range(start, end + 1)}
    late_manual = [
        station["id"]
        for station in stations
        if station["archetype"] == "MANUAL"
        and station["id"] not in dark_members
        and station["id"] > (corridors[-1][1] if corridors else 0)
    ]
    if late_manual:
        checkpoints.append(
            {
                "id": "CP_LIGHT_FINAL_RFID",
                "stationId": late_manual[0],
                "type": "RFID",
                "progress": 0.5,
                "reliability": round(rng.uniform(0.90, 0.95), 2),
                "falsePositiveRate": 0.01,
                "identifiesUnit": True,
            }
        )

    # Segment labels were scaffolding for naming and zone titles; they are not part of
    # the simulator's station contract.
    for station in stations:
        station.pop("_segment", None)

    factory = {
        DEMO_MARKER: True,
        "_generated_by": GENERATOR_ID,
        "_generator_version": GENERATOR_VERSION,
        "_seed": seed,
        "_note": DEMO_NOTE,
        "stations": stations,
        "darkZones": dark_zones,
        "checkpoints": checkpoints,
    }

    validation = validate_factory(factory)
    if not validation.ok:
        raise RuntimeError(
            "demo factory generator produced an invalid factory for seed "
            f"{seed}: {'; '.join(validation.errors)}"
        )
    if validation.warnings:
        raise RuntimeError(
            "demo factory generator violated its own demo policy for seed "
            f"{seed}: {'; '.join(validation.warnings)}"
        )
    return factory


def is_demo_factory(data: Any) -> bool:
    """Return True when a factory payload was produced by this generator."""
    return isinstance(data, dict) and data.get(DEMO_MARKER) is True
